# Generated by Django 4.2.6 on 2023-10-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mid_name",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="user",
            name="prefix",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
