# Generated by Django 4.2.6 on 2023-10-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date_of_publish",
            field=models.DateField(auto_now=True),
        ),
    ]
