# Generated by Django 4.2.6 on 2023-10-07 22:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_initial"),
        ("topics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="recommendation",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="recommendations.recommendation",
            ),
            preserve_default=False,
        ),
    ]
